### ISSUE TITLE
SIGSEGV Error When Testing with Spring Music App

### ISSUE THREAD

**Issue by jloar-pivotal** [cloudfoundry/cpu-entitlement-plugin#16]
Hi Team,

I ran into the following error when testing this plugin with the [spring music app](https://github.com/cloudfoundry-samples/spring-music). @dmikusa-pivotal also tested this and had the same result.

I'm testing this using PAS 2.8 build 148 which is using `garden-runc 1.19.8`.

Go version is 1.13.4
```➜  cpu-entitlement-plugin git:(master) go version
go version go1.13.4 darwin/amd64
```

```
spring-music git:(master) cf cpu-entitlement spring-music
Note: This feature is experimental.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f1a5c]

goroutine 1 [running]:
code.cloudfoundry.org/cpu-entitlement-plugin/fetchers.parseLastSpike(0xc000336d20, 0x2, 0x2, 0xc0001f9830, 0x24, 0xbf6343b1a3ecda88, 0xfff67c0267ccbad6)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/fetchers/last_spike.go:52 +0x14c
code.cloudfoundry.org/cpu-entitlement-plugin/fetchers.LastSpikeFetcher.FetchInstanceData(0x17214e0, 0xc00014a7d0, 0xbf6343b1a3ecda88, 0xfff67c0267ccbad6, 0x1b1b360, 0xc00009cb40, 0x24, 0xc0001f9830, 0x0, 0x1011032, ...)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/fetchers/last_spike.go:35 +0x1f4
code.cloudfoundry.org/cpu-entitlement-plugin/reporter.AppReporter.CreateApplicationReport(0x1718ae0, 0xc00000cac0, 0x1717640, 0xc00011b500, 0x1718ac0, 0xc00005c7d0, 0x1725a20, 0xc00000caa0, 0x7ffeefbff7bc, 0xc, ...)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/reporter/app_reporter.go:128 +0x613
code.cloudfoundry.org/cpu-entitlement-plugin/plugins.AppRunner.Run(0x1718b40, 0xc00001e900, 0x1718b20, 0xc00005c7f0, 0x7ffeefbff7bc, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/plugins/app_runner.go:35 +0x85
code.cloudfoundry.org/cpu-entitlement-plugin/plugins.CPUEntitlementPlugin.Run(0x172e0e0, 0xc00007ead0, 0xc0000a4060, 0x2, 0x2)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/plugins/app_plugin.go:74 +0xa3d
code.cloudfoundry.org/cli/plugin.Start(0x171d660, 0x1b38278)
	/tmp/build/9971d0f2/cpu-entitlement-plugin/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x284
main.main()
	/tmp/build/9971d0f2/cpu-entitlement-plugin/cmd/cpu-entitlement/main.go:9 +0x39
```

I've also tested this using the [articulate app](https://github.com/pivotal-education/pcf-articulate-code). I was able to get the proper result of using `cf cpu-entitlement articulate` for a few minutes and then I get the same SIGSEGV error as above.

```
 pcf-articulate-code git:(master) ✗ cf cpu-entitlement articulate
Note: This feature is experimental.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f5b7f]

goroutine 1 [running]:
code.cloudfoundry.org/cpu-entitlement-plugin/fetchers.parseLastSpike(0xc00024ac00, 0x4, 0x4, 0xc00011b410, 0x24, 0xbf6344d599342600, 0xfff67c0267d2c82a)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/fetchers/last_spike.go:65 +0x1cf
code.cloudfoundry.org/cpu-entitlement-plugin/fetchers.LastSpikeFetcher.FetchInstanceData(0x17277c0, 0xc0001d60a0, 0xbf6344d599342600, 0xfff67c0267d2c82a, 0x1b2a700, 0xc00012a9f0, 0x24, 0xc00011b410, 0x0, 0x10130b2, ...)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/fetchers/last_spike.go:39 +0x1f4
code.cloudfoundry.org/cpu-entitlement-plugin/reporter.AppReporter.CreateApplicationReport(0x171eae0, 0xc000112520, 0x171d660, 0xc0001104e0, 0x171eac0, 0xc000114210, 0x172bcc0, 0xc000112500, 0x7ffeefbff7b4, 0xa, ...)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/reporter/app_reporter.go:128 +0x613
code.cloudfoundry.org/cpu-entitlement-plugin/plugins.AppRunner.Run(0x171eb40, 0xc00011e140, 0x171eb20, 0xc000114230, 0x7ffeefbff7b4, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/plugins/app_runner.go:35 +0x85
code.cloudfoundry.org/cpu-entitlement-plugin/plugins.CPUEntitlementPlugin.Run(0x1734160, 0xc000164f20, 0xc0000ba020, 0x2, 0x2)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/plugins/app_plugin.go:74 +0xa3d
code.cloudfoundry.org/cli/plugin.Start(0x17236c0, 0x1b47638)
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x284
main.main()
	/Users/jloar/workspace/pez-lab-pipelines-new/lab37/cpu-entitlement-plugin/cmd/cpu-entitlement/main.go:9 +0x39
```

**Comment by yulianedyalkova** [comment]
Hello! Thanks for opening the issue!

Could you build the latest version of the plugin as described [here](https://github.com/cloudfoundry/cpu-entitlement-plugin#building) and see if the issue happens again?

**Comment by jloar-pivotal** [comment]
Hi Julia,

I have updated the plugin to the latest version and it is working great now. I'm not seeing any SIGSEGV errors.

```
➜  spring-music git:(master) cf cpu-entitlement spring-music
Note: This feature is experimental.
Showing CPU usage against entitlement for app spring-music in org test / space jloar as admin ...

     avg usage   curr usage
#0   83.35%      0.90%
```

Tested it over a period of 5 minutes and it continues to work properly.

Thank you for the fix!
